//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ProductName { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
